name: project_sih
description: "Smart Tourist Safety Monitoring & Incident Response System"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.2.1
  flutter_contacts: ^1.1.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
